tunnel: TUNNEL_NAME
credentials-file: /home/USERNAME/.cloudflared/LONG_RANDOM_STRING.json

ingress:
  - hostname: example.com
    service: http://localhost:4000
  - hostname: hooks.example.com
    service: http://localhost:9000
  - service: http_status:404
